###

GET http://localhost:4000/

###

POST http://localhost:3000/signup
Content-Type: application/json

{
    "userId": "user134",
    "name": "Maxcimian",
    "password": "securepassword"
}



###
POST http://localhost:4000/login
Content-Type: application/json

{
    "userId": "user123",
    "password": "securepassword"
}


###
POST http://localhost:3000/stations
Content-Type: application/json

 {
    "stationId": "ST105",
    "name": "Station Nova",
    "location": "Hyderabad",
    "userId": 15
  }


###
GET http://localhost:3000/stations
Authorization: Bearer 

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token":""
}